services:
  - type: web
    name: acquiremock-gateway
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

      - key: DATABASE_URL
        sync: false

      - key: WEBHOOK_SECRET
        generateValue: true

      - key: BREVO_API_KEY
        sync: false

      - key: BREVO_FROM_EMAIL
        value: noreply@acquiremock.com

      - key: BREVO_FROM_NAME
        value: AcquireMock